//getElement by ID

let msg=document.getElementById("main-heading")
console.log(msg)

//get Elemnets by  classname
let listItems =document.getElementsByClassName("list-items")
console.log(listItems)

//get Element by tag name
const listItem =document.getElementsByTagName("ul")
console.log(listItem)

const container =document.querySelector('div');
console.log(container);

// #main-heading is used for ID selector
// .main-heading is used for class selector 
// main-heading is used  for tag selector

const title= document.querySelector('.main-heading');
title.querySelector.color ='red';
title.style.color ='red'; // from this it can change the color of style
//console.log(title.style.color)
console.log(title.querySelector.color)

//change the font-size 
const list_items = document.querySelectorAll('.list-items');
for(i=0; i< list_items.length;i++){
    list_items[i].style.fontSize ='2rem';
    
}
console.log(list_items)

//creating Elements
const ul =document.querySelector('ul');
const li =document.createElement('li');
//adding elements
ul.append(li);
//modifying text
li.innerText = 'X-man';
//Modifying attributes & classes => here X-man becomes to blue color
//li.setAttribute('class','main-heading');

//classList Methods
//classList Add method
li.classList.add('list-items');
//when li.classList.add('list-items');=> returns true else li.classList.remove('list-items');=> returns false
console.log(li.classList.contains('list-items')) 
//querySelector selects the first element of the list-items group
const firstListItem=document.querySelector('.list-items');

//This logs the visible text content of the selected element.
//It does not include hidden text or text generated by CSS, and it represents what's visually rendered(process of displaying or presenting).
console.log(firstListItem.innerText);
//This also logs the text content of the selected element. Unlike innerText, it includes hidden text and text generated by CSS, giving you the complete text content.
console.log(firstListItem.textContent);
//This logs the HTML content of the selected element, including any HTML tags inside the element.
console.log(firstListItem.innerHTML);

const title2=document.querySelector('#main-heading2');
console.log(title2.getAttribute('id'));